--LIQUIBASE FORMATTED SQL
--CHANGESET ME:CREATE_SONGS_TABLE
CREATE OR REPLACE TABLE sys.SONGS (
	UID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	SONG_NAME VARCHAR(128) NOT NULL,
	PRIMARY_ARTIST_ID BIGINT UNSIGNED NULL,
	URL VARCHAR(512) NULL
);
--ROLLBACK EMPTY


--CHANGESET ME:CREATE_ARTISTS_TABLE
CREATE OR REPLACE TABLE sys.ARTISTS (
	UID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	ARTIST_NAME VARCHAR(64) NOT NULL
);
--ROLLBACK EMPTY


--CHANGESET ME:CREATE_SONGS_AND_ARTISTS_TABLE
CREATE OR REPLACE TABLE sys.SONG_AND_ARTISTS (
	UID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	SONG_ID BIGINT UNSIGNED NOT NULL,
	ARTIST_ID BIGINT UNSIGNED NOT NULL
);
--ROLLBACK EMPTY


--CHANGESET ME:CREATE_USERS_TABLE
CREATE OR REPLACE TABLE sys.USERS (
	USER_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	USER_NAME VARCHAR(32) NOT NULL,
	PASS_HASH VARCHAR(255) NOT NULL
);
--ROLLBACK EMPTY



-- if you need to create the DB that the above references
--CREATE OR REPLACE DATABASE rust_api;